--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Rushil13579/SellXp
build-by-default: true
branches:
- main
projects:
  SellXp:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    icon: Logo.png
...
