# SELLXP PLUGIN
# MADE BY: Rushil13579 | Rushil#2326

# MESSAGE TO BE SENT IF THE PLAYER DOESNT HAVE ENOUGH XP!
not-enough-xp-msg: "§cYou do not have enough Xp!"

# MESSAGE TO BE SENT IF THE ARGUMENT GIVEN BY THE PLAYER IS NOT A NUMBER!
non-numeric-argument: "§cPlease enter a integer!"

# MESSAGE TO BE SENT IF THE ARGUMENT GIVEN BY THE PLAYER IS NOT A INTEGER!
non-integer-given: "§cPlease enter a integer"

# MESSAGE TO BE SENT WHEN THE PLAYER SELLS XP [USE {xp} FOR AMOUNT OF XP SOLD AND USE {amount} FOR SELLING AMOUNT]
sellxp-msg: "§bSold §6{xp} §bfor §6{amount}"

# AMOUNT FOR EACH LEVEL OF XP! [XP-MONEY EXCHANGE RATE]
amount-per-xp: "10"

# IN-CASE OF ANY BUGS CONTACT THE OWNER AT THE ABOVE DETAILS!